theme: jekyll-theme-cayman
markdown: karmdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
